services:
  psql:
    image: postgres:10
    environment:
      POSTGRES_DB: cc-portal
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local