services:
  psql:
    image: postgres:10
    environment:
      POSTGRES_DB: cc-portal
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  s3:
    image: minio/minio
    container_name: minio_local_cc
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: bloxico
      MINIO_ROOT_PASSWORD: bloxico2
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - s3_data:/data
    networks:
      - bloxico_local
volumes:
  cache:
    driver: local
  s3_data: 
    driver: local
networks:
  bloxico_local: # Custom network for the bloxico service
    driver: bridge