export const ICONS = {
  rocketLaunch: "/icons/RocketLaunch.svg",
  arrowDown: "/icons/ArrowDown.svg",
  upload: "/icons/Upload.svg",
  close: "/icons/Close.svg",
  chevronDown: "/icons/ChevronDown.svg",
  edit: "/icons/Edit.svg",
  logout: "/icons/Logout.svg",
  help: "/icons/Help.svg",
  menuIcon: "/icons/MenuIcon.svg",
  arrowUpRight: "/icons/ArrowUpRight.svg",
  copyIcon: "/icons/Copy.svg",
  arrowRight: "/icons/ArrowRight.svg",
  arrowLeft: "/icons/ArrowLeft.svg",
  favicon: "/icons/Favicon.ico",
  logoSign: "/icons/LogoSign.svg",
  informationCircle: "/icons/InformationCircle.svg",
  filter: "/icons/Filter.svg",
  filterWhite: "/icons/FilterWhite.svg",
  sort: "/icons/Sort.svg",
  sortActive: "/icons/SortActive.svg",
  sortWhite: "/icons/SortWhite.svg",
  govAction: "/icons/GovAction.svg",
  externalLink: "/icons/ExternalLink.svg",
};
