export const IMAGES = {
  logoSign: "/images/LogoSign.png",
  heroImage: "/images/HeroImage.png",
  menuIcon: "/images/MenuIcon.png",
  arrowLeft: "/images/ArrowLeft.png",
  arrowRight: "/images/ArrowRight.png",
  login: "/images/Login.png",
  bookOpen: "/images/BookOpen.png",
  pastelSignIn: "/images/PastelSignIn.png",
  pastelDeleteRole: "/images/PastelDeleteRole.png",
  pastelAddMember: "/images/PastelAddMember.png",
  pastelSignOut: "/images/PastelSignOut.png",
  avatar: "/images/Avatar.svg",
  mail: "/images/Mail.png",
};
