export const CIP136 = {
  contextLanguage: 'en-us',
  contextCIP100:
    'https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#',
  contextCIP136:
    'https://github.com/cardano-foundation/CIPs/blob/master/CIP-0136/README.md#',
  contextHashAlgorithm: 'CIP100:hashAlgorithm',
  contextBody: 'CIP136:body',
  contextBodyReferences: 'CIP100:references',
  contextBodyReferencesGovernanceMetadata: 'CIP100:GovernanceMetadataReference',
  contextBodyReferencesOther: 'CIP100:OtherReference',
  contextBodyReferencesLabel: 'CIP100:reference-label',
  contextBodyReferencesUri: 'CIP100:reference-uri',
  contextBodyReferencesRelevantArticles: 'CIP136:RelevantArticles',
  contextBodySummary: 'CIP136:summary',
  contextBodyRationaleStatement: 'CIP136:rationaleStatement',
  contextBodyPrecedentDiscussion: 'CIP136:precedentDiscussion',
  contextBodyCounterargumentDiscussion: 'CIP136:counterargumentDiscussion',
  contextBodyConclusion: 'CIP136:conclusion',
  contextBodyInternalVote: 'CIP136:internalVote',
  contextBodyInternalVoteConstitutional: 'CIP136:constitutional',
  contextBodyInternalVoteUnconstitutional: 'CIP136:unconstitutional',
  contextBodyInternalVoteAbstain: 'CIP136:abstain',
  contextBodyInternalVoteDidNotVote: 'CIP136:didNotVote',
  contextAuthors: 'CIP100:authors',
  contextAuthorsName: 'http://xmlns.com/foaf/0.1/name',
  contextAuthorsWitness: 'CIP100:witness',
  contextWitnessAlgorithm: 'CIP100:witnessAlgorithm',
  contextWitnessPublicKey: 'CIP100:publicKey',
  contextWitnessSignature: 'CIP100:signature',
  hashAlgorithm: 'blake2b-256',
};
