name: CI-develop-branch

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  deploy_to_do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            eval `ssh-agent -s`
            ssh-add cc
            cd cc-portal \
            && git pull origin develop \
            && docker compose up -d --force-recreate --build \
            && docker container exec -it postgres sh \
            && psql -U BEdev24 -d cc-portal \
               -c "
               - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            eval `ssh-agent -s`
            ssh-add cc
            cd cc-portal \
            && git pull origin develop \
            && docker compose up down -v \
            && docker image rm $(docker image ls) \
            && docker compose up -d \
            && docker container exec -i backend npm run typeorm:run-migrations \
            && docker container exec -i postgres psql -U BEdev24 -d cc-portal \
            -c "
            INSERT INTO users (email, status, role_id) VALUES ('developer@bloxico.com', 'active', 
            (SELECT r.id FROM roles r WHERE r.code='super_admin'));

            INSERT INTO user_permissions(user_id, permission_id)
            SELECT users.id, permissions.id
            FROM permissions
            INNER join users on users.email 
            IN ('developer@bloxico.com')
            WHERE code IN ('manage_cc_members', 'add_constitution_version', 'add_new_admin')
            "
    
