name: CI-develop-branch

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  deploy_to_do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: develop

        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            eval `ssh-agent -s`
            ssh-add cc
            cd cc-portal \
            && git pull origin develop \
            && docker compose up -d --build --force-recreate \
            && docker image rm $(docker image ls -f "dangling=true")
    
